//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clima
    {
        public int ClimaId { get; set; }
        public string Localidad { get; set; }
        public double Temperatura { get; set; }
        public double Trecipitaciones { get; set; }
        public double Viento { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> TiempoAtmosférico { get; set; }
    }
}
